### ISSUE TITLE
JAVA

### ISSUE THREAD

**Issue by AndreaTorti-01** [AndreaTorti-01/Auto_Paper#3]
if the java required installation is missing, it should download and install it, or at least help the user with it

https://pypi.org/project/install-jdk/ maybe? but I want the jre, not necessarily the jdk

**Comment by NehaK275** [comment]
hi @AndreaTorti-01 can i solve this?

**Comment by AndreaTorti-01** [comment]
Yes you can! Thanks for the interest!

Il ven 4 mar 2022, 10:02 NehaK275 ***@***.***> ha scritto:
